//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public campaign()
        {
            this.compaignVolunteerRelationships = new HashSet<compaignVolunteerRelationship>();
            this.events = new HashSet<@event>();
            this.pageInchargeAssignedAreas = new HashSet<pageInchargeAssignedArea>();
            this.pollingBooth_andInchargRelationship = new HashSet<pollingBooth_andInchargRelationship>();
            this.surveys = new HashSet<survey>();
        }
    
        public long campaignID { get; set; }
        public string campaignName { get; set; }
        public int electionTypeID { get; set; }
        public int electionID { get; set; }
        public int politicalPartyID { get; set; }
        public Nullable<int> lokSabhaConstituencyID { get; set; }
        public Nullable<int> vidhanSabhaConstituencyID { get; set; }
        public Nullable<int> wardID { get; set; }
        public long volunteerID { get; set; }
        public System.DateTime dataIsCreated { get; set; }
        public System.DateTime dataIsUpdated { get; set; }
        public long createdBy { get; set; }
        public long modifiedBy { get; set; }
        public bool isActive { get; set; }
        public bool isOLD { get; set; }
        public bool isPaymentComplete { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual electionName electionName { get; set; }
        public virtual electionType electionType { get; set; }
        public virtual loginVolunteer loginVolunteer { get; set; }
        public virtual loginVolunteer loginVolunteer1 { get; set; }
        public virtual lokSabhaConstituency lokSabhaConstituency { get; set; }
        public virtual politicalParty politicalParty { get; set; }
        public virtual vidhanSabhaConstituency vidhanSabhaConstituency { get; set; }
        public virtual volunteerList volunteerList { get; set; }
        public virtual wardConstituency wardConstituency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compaignVolunteerRelationship> compaignVolunteerRelationships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<@event> events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pageInchargeAssignedArea> pageInchargeAssignedAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pollingBooth_andInchargRelationship> pollingBooth_andInchargRelationship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<survey> surveys { get; set; }
    }
}
