//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class electoEntities : DbContext
    {
        public electoEntities()
            : base("name=electoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<areaName> areaNames { get; set; }
        public virtual DbSet<Biography_s> Biography_s { get; set; }
        public virtual DbSet<campaignPrice> campaignPrices { get; set; }
        public virtual DbSet<campaign> campaigns { get; set; }
        public virtual DbSet<compaignVolunteerRelationship> compaignVolunteerRelationships { get; set; }
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<electionName> electionNames { get; set; }
        public virtual DbSet<electionType> electionTypes { get; set; }
        public virtual DbSet<enquiry> enquiries { get; set; }
        public virtual DbSet<enquiryType> enquiryTypes { get; set; }
        public virtual DbSet<eventMedia> eventMedias { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<eventType> eventTypes { get; set; }
        public virtual DbSet<excel> excels { get; set; }
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<language> languages { get; set; }
        public virtual DbSet<loginVolunteer> loginVolunteers { get; set; }
        public virtual DbSet<lokSabhaConstituency> lokSabhaConstituencies { get; set; }
        public virtual DbSet<monthName> monthNames { get; set; }
        public virtual DbSet<municipalCorporationName> municipalCorporationNames { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<pageInchargeAssignedArea> pageInchargeAssignedAreas { get; set; }
        public virtual DbSet<pageInchargeComment> pageInchargeComments { get; set; }
        public virtual DbSet<politicalParty> politicalParties { get; set; }
        public virtual DbSet<politicalPartyAddress> politicalPartyAddresses { get; set; }
        public virtual DbSet<pollingBooth> pollingBooths { get; set; }
        public virtual DbSet<pollingBooth_andInchargRelationship> pollingBooth_andInchargRelationship { get; set; }
        public virtual DbSet<questionType> questionTypes { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<survey> surveys { get; set; }
        public virtual DbSet<SurveyQuestionOption> SurveyQuestionOptions { get; set; }
        public virtual DbSet<surveyQuestion> surveyQuestions { get; set; }
        public virtual DbSet<surveyRespons> surveyResponses { get; set; }
        public virtual DbSet<tblyear> tblyears { get; set; }
        public virtual DbSet<userType> userTypes { get; set; }
        public virtual DbSet<vidhanSabhaConstituency> vidhanSabhaConstituencies { get; set; }
        public virtual DbSet<volunteerList> volunteerLists { get; set; }
        public virtual DbSet<voterList> voterLists { get; set; }
        public virtual DbSet<wardConstituency> wardConstituencies { get; set; }
        public virtual DbSet<zoneMunicipality> zoneMunicipalities { get; set; }
        public virtual DbSet<sendGridDetail> sendGridDetails { get; set; }
        public virtual DbSet<userRight> userRights { get; set; }
    
        public virtual ObjectResult<sp_electionList_Result> sp_electionList(Nullable<int> electionType, Nullable<int> ddl_year, Nullable<int> ddl_month)
        {
            var electionTypeParameter = electionType.HasValue ?
                new ObjectParameter("ElectionType", electionType) :
                new ObjectParameter("ElectionType", typeof(int));
    
            var ddl_yearParameter = ddl_year.HasValue ?
                new ObjectParameter("ddl_year", ddl_year) :
                new ObjectParameter("ddl_year", typeof(int));
    
            var ddl_monthParameter = ddl_month.HasValue ?
                new ObjectParameter("ddl_month", ddl_month) :
                new ObjectParameter("ddl_month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_electionList_Result>("sp_electionList", electionTypeParameter, ddl_yearParameter, ddl_monthParameter);
        }
    
        public virtual ObjectResult<sp_GetNewCampaignRequests_Result> sp_GetNewCampaignRequests()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetNewCampaignRequests_Result>("sp_GetNewCampaignRequests");
        }
    
        public virtual int sp_GetNewEnquiries(string enquirytype, Nullable<System.DateTime> date, string mobile, Nullable<bool> isTaskCompleted)
        {
            var enquirytypeParameter = enquirytype != null ?
                new ObjectParameter("enquirytype", enquirytype) :
                new ObjectParameter("enquirytype", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            var isTaskCompletedParameter = isTaskCompleted.HasValue ?
                new ObjectParameter("isTaskCompleted", isTaskCompleted) :
                new ObjectParameter("isTaskCompleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetNewEnquiries", enquirytypeParameter, dateParameter, mobileParameter, isTaskCompletedParameter);
        }
    
        public virtual ObjectResult<sp_GetRunningCampaigns_Result> sp_GetRunningCampaigns()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRunningCampaigns_Result>("sp_GetRunningCampaigns");
        }
    
        public virtual int sp_RequestedCampaignList(string electiontype, string partyname, string year, string campaignname)
        {
            var electiontypeParameter = electiontype != null ?
                new ObjectParameter("electiontype", electiontype) :
                new ObjectParameter("electiontype", typeof(string));
    
            var partynameParameter = partyname != null ?
                new ObjectParameter("partyname", partyname) :
                new ObjectParameter("partyname", typeof(string));
    
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            var campaignnameParameter = campaignname != null ?
                new ObjectParameter("campaignname", campaignname) :
                new ObjectParameter("campaignname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RequestedCampaignList", electiontypeParameter, partynameParameter, yearParameter, campaignnameParameter);
        }
    
        public virtual int sp_SearchRunningCampaigns(string electiontype, string partyname, string year, string campaignname)
        {
            var electiontypeParameter = electiontype != null ?
                new ObjectParameter("electiontype", electiontype) :
                new ObjectParameter("electiontype", typeof(string));
    
            var partynameParameter = partyname != null ?
                new ObjectParameter("partyname", partyname) :
                new ObjectParameter("partyname", typeof(string));
    
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            var campaignnameParameter = campaignname != null ?
                new ObjectParameter("campaignname", campaignname) :
                new ObjectParameter("campaignname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SearchRunningCampaigns", electiontypeParameter, partynameParameter, yearParameter, campaignnameParameter);
        }
    
        public virtual ObjectResult<sp_SearchUpcomingElections_Result> sp_SearchUpcomingElections(string electiontype, string year)
        {
            var electiontypeParameter = electiontype != null ?
                new ObjectParameter("electiontype", electiontype) :
                new ObjectParameter("electiontype", typeof(string));
    
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchUpcomingElections_Result>("sp_SearchUpcomingElections", electiontypeParameter, yearParameter);
        }
    
        public virtual ObjectResult<sp_areaList_Result> sp_areaList(Nullable<int> stateID, Nullable<int> electionTypeID, Nullable<int> constituencyID)
        {
            var stateIDParameter = stateID.HasValue ?
                new ObjectParameter("stateID", stateID) :
                new ObjectParameter("stateID", typeof(int));
    
            var electionTypeIDParameter = electionTypeID.HasValue ?
                new ObjectParameter("electionTypeID", electionTypeID) :
                new ObjectParameter("electionTypeID", typeof(int));
    
            var constituencyIDParameter = constituencyID.HasValue ?
                new ObjectParameter("constituencyID", constituencyID) :
                new ObjectParameter("constituencyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_areaList_Result>("sp_areaList", stateIDParameter, electionTypeIDParameter, constituencyIDParameter);
        }
    
        public virtual ObjectResult<sp_getVidhanSabhaLsit_Result> sp_getVidhanSabhaLsit(Nullable<int> stateId, Nullable<int> lokSabhaId, string vidhanSabhaName)
        {
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("stateId", stateId) :
                new ObjectParameter("stateId", typeof(int));
    
            var lokSabhaIdParameter = lokSabhaId.HasValue ?
                new ObjectParameter("lokSabhaId", lokSabhaId) :
                new ObjectParameter("lokSabhaId", typeof(int));
    
            var vidhanSabhaNameParameter = vidhanSabhaName != null ?
                new ObjectParameter("vidhanSabhaName", vidhanSabhaName) :
                new ObjectParameter("vidhanSabhaName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getVidhanSabhaLsit_Result>("sp_getVidhanSabhaLsit", stateIdParameter, lokSabhaIdParameter, vidhanSabhaNameParameter);
        }
    
        public virtual ObjectResult<sp_pollingBoothList_Result> sp_pollingBoothList(Nullable<int> stateId, Nullable<int> lokSabhaId, Nullable<int> vidhansabhaID, Nullable<int> wardID)
        {
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("stateId", stateId) :
                new ObjectParameter("stateId", typeof(int));
    
            var lokSabhaIdParameter = lokSabhaId.HasValue ?
                new ObjectParameter("lokSabhaId", lokSabhaId) :
                new ObjectParameter("lokSabhaId", typeof(int));
    
            var vidhansabhaIDParameter = vidhansabhaID.HasValue ?
                new ObjectParameter("vidhansabhaID", vidhansabhaID) :
                new ObjectParameter("vidhansabhaID", typeof(int));
    
            var wardIDParameter = wardID.HasValue ?
                new ObjectParameter("wardID", wardID) :
                new ObjectParameter("wardID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_pollingBoothList_Result>("sp_pollingBoothList", stateIdParameter, lokSabhaIdParameter, vidhansabhaIDParameter, wardIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_createParty(string politicalPartyName, string politicalPartyLogo, string politicalPartyWebsiteUrl, string politicalPartyEmail, Nullable<System.DateTime> dataIsCreated, Nullable<long> createdBy, Nullable<int> districtID, Nullable<int> stateID, string plotNo, string streetNo, string address1, string address2, string pincode, string telephone)
        {
            var politicalPartyNameParameter = politicalPartyName != null ?
                new ObjectParameter("politicalPartyName", politicalPartyName) :
                new ObjectParameter("politicalPartyName", typeof(string));
    
            var politicalPartyLogoParameter = politicalPartyLogo != null ?
                new ObjectParameter("politicalPartyLogo", politicalPartyLogo) :
                new ObjectParameter("politicalPartyLogo", typeof(string));
    
            var politicalPartyWebsiteUrlParameter = politicalPartyWebsiteUrl != null ?
                new ObjectParameter("politicalPartyWebsiteUrl", politicalPartyWebsiteUrl) :
                new ObjectParameter("politicalPartyWebsiteUrl", typeof(string));
    
            var politicalPartyEmailParameter = politicalPartyEmail != null ?
                new ObjectParameter("politicalPartyEmail", politicalPartyEmail) :
                new ObjectParameter("politicalPartyEmail", typeof(string));
    
            var dataIsCreatedParameter = dataIsCreated.HasValue ?
                new ObjectParameter("dataIsCreated", dataIsCreated) :
                new ObjectParameter("dataIsCreated", typeof(System.DateTime));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(long));
    
            var districtIDParameter = districtID.HasValue ?
                new ObjectParameter("districtID", districtID) :
                new ObjectParameter("districtID", typeof(int));
    
            var stateIDParameter = stateID.HasValue ?
                new ObjectParameter("stateID", stateID) :
                new ObjectParameter("stateID", typeof(int));
    
            var plotNoParameter = plotNo != null ?
                new ObjectParameter("plotNo", plotNo) :
                new ObjectParameter("plotNo", typeof(string));
    
            var streetNoParameter = streetNo != null ?
                new ObjectParameter("streetNo", streetNo) :
                new ObjectParameter("streetNo", typeof(string));
    
            var address1Parameter = address1 != null ?
                new ObjectParameter("address1", address1) :
                new ObjectParameter("address1", typeof(string));
    
            var address2Parameter = address2 != null ?
                new ObjectParameter("address2", address2) :
                new ObjectParameter("address2", typeof(string));
    
            var pincodeParameter = pincode != null ?
                new ObjectParameter("pincode", pincode) :
                new ObjectParameter("pincode", typeof(string));
    
            var telephoneParameter = telephone != null ?
                new ObjectParameter("telephone", telephone) :
                new ObjectParameter("telephone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_createParty", politicalPartyNameParameter, politicalPartyLogoParameter, politicalPartyWebsiteUrlParameter, politicalPartyEmailParameter, dataIsCreatedParameter, createdByParameter, districtIDParameter, stateIDParameter, plotNoParameter, streetNoParameter, address1Parameter, address2Parameter, pincodeParameter, telephoneParameter);
        }
    
        public virtual ObjectResult<sp_politicalPartyList_Result> sp_politicalPartyList(Nullable<int> stateId, string partyName)
        {
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("stateId", stateId) :
                new ObjectParameter("stateId", typeof(int));
    
            var partyNameParameter = partyName != null ?
                new ObjectParameter("partyName", partyName) :
                new ObjectParameter("partyName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_politicalPartyList_Result>("sp_politicalPartyList", stateIdParameter, partyNameParameter);
        }
    
        public virtual ObjectResult<sp_partyAddressList_Result> sp_partyAddressList(Nullable<int> politicalPartyID)
        {
            var politicalPartyIDParameter = politicalPartyID.HasValue ?
                new ObjectParameter("politicalPartyID", politicalPartyID) :
                new ObjectParameter("politicalPartyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_partyAddressList_Result>("sp_partyAddressList", politicalPartyIDParameter);
        }
    
        public virtual int sp_SearchCampaignPrices(string electiontype, string year, Nullable<bool> isActive)
        {
            var electiontypeParameter = electiontype != null ?
                new ObjectParameter("electiontype", electiontype) :
                new ObjectParameter("electiontype", typeof(string));
    
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SearchCampaignPrices", electiontypeParameter, yearParameter, isActiveParameter);
        }
    
        public virtual int sp_AddNewCampaignPrice(Nullable<int> electiontype, string year, Nullable<int> price, Nullable<System.DateTime> dataIsCreated, Nullable<System.DateTime> dataIsUpdated, Nullable<long> createdBy, Nullable<long> modifiedBy, Nullable<bool> isActive)
        {
            var electiontypeParameter = electiontype.HasValue ?
                new ObjectParameter("electiontype", electiontype) :
                new ObjectParameter("electiontype", typeof(int));
    
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(int));
    
            var dataIsCreatedParameter = dataIsCreated.HasValue ?
                new ObjectParameter("dataIsCreated", dataIsCreated) :
                new ObjectParameter("dataIsCreated", typeof(System.DateTime));
    
            var dataIsUpdatedParameter = dataIsUpdated.HasValue ?
                new ObjectParameter("dataIsUpdated", dataIsUpdated) :
                new ObjectParameter("dataIsUpdated", typeof(System.DateTime));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(long));
    
            var modifiedByParameter = modifiedBy.HasValue ?
                new ObjectParameter("modifiedBy", modifiedBy) :
                new ObjectParameter("modifiedBy", typeof(long));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddNewCampaignPrice", electiontypeParameter, yearParameter, priceParameter, dataIsCreatedParameter, dataIsUpdatedParameter, createdByParameter, modifiedByParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_resetPassword(Nullable<long> loginID, string password)
        {
            var loginIDParameter = loginID.HasValue ?
                new ObjectParameter("loginID", loginID) :
                new ObjectParameter("loginID", typeof(long));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_resetPassword", loginIDParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_Campaigns_GetAll_Result> sp_Campaigns_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Campaigns_GetAll_Result>("sp_Campaigns_GetAll");
        }
    
        public virtual ObjectResult<sp_Campaigns_GetByElectionTypeId_Result> sp_Campaigns_GetByElectionTypeId(Nullable<long> electionTypeId)
        {
            var electionTypeIdParameter = electionTypeId.HasValue ?
                new ObjectParameter("ElectionTypeId", electionTypeId) :
                new ObjectParameter("ElectionTypeId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Campaigns_GetByElectionTypeId_Result>("sp_Campaigns_GetByElectionTypeId", electionTypeIdParameter);
        }
    
        public virtual ObjectResult<sp_ageWiseVoterCountInConstituency_Result> sp_ageWiseVoterCountInConstituency(Nullable<int> vidhanSabhaConstituencyID, Nullable<int> lokSabhaConstituencyID, Nullable<int> wardID, Nullable<int> areaID, Nullable<int> year)
        {
            var vidhanSabhaConstituencyIDParameter = vidhanSabhaConstituencyID.HasValue ?
                new ObjectParameter("vidhanSabhaConstituencyID", vidhanSabhaConstituencyID) :
                new ObjectParameter("vidhanSabhaConstituencyID", typeof(int));
    
            var lokSabhaConstituencyIDParameter = lokSabhaConstituencyID.HasValue ?
                new ObjectParameter("lokSabhaConstituencyID", lokSabhaConstituencyID) :
                new ObjectParameter("lokSabhaConstituencyID", typeof(int));
    
            var wardIDParameter = wardID.HasValue ?
                new ObjectParameter("wardID", wardID) :
                new ObjectParameter("wardID", typeof(int));
    
            var areaIDParameter = areaID.HasValue ?
                new ObjectParameter("areaID", areaID) :
                new ObjectParameter("areaID", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ageWiseVoterCountInConstituency_Result>("sp_ageWiseVoterCountInConstituency", vidhanSabhaConstituencyIDParameter, lokSabhaConstituencyIDParameter, wardIDParameter, areaIDParameter, yearParameter);
        }
    
        public virtual ObjectResult<sp_Campaigns_GetByElectionId_Result> sp_Campaigns_GetByElectionId(Nullable<long> electionId)
        {
            var electionIdParameter = electionId.HasValue ?
                new ObjectParameter("ElectionId", electionId) :
                new ObjectParameter("ElectionId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Campaigns_GetByElectionId_Result>("sp_Campaigns_GetByElectionId", electionIdParameter);
        }
    
        public virtual ObjectResult<sp_Campaigns_GetById_Result> sp_Campaigns_GetById(Nullable<long> campaignId)
        {
            var campaignIdParameter = campaignId.HasValue ?
                new ObjectParameter("CampaignId", campaignId) :
                new ObjectParameter("CampaignId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Campaigns_GetById_Result>("sp_Campaigns_GetById", campaignIdParameter);
        }
    
        public virtual ObjectResult<sp_Campaigns_GetByLokSabhaConstituencyId_Result> sp_Campaigns_GetByLokSabhaConstituencyId(Nullable<long> lokSabhaConstituencyId)
        {
            var lokSabhaConstituencyIdParameter = lokSabhaConstituencyId.HasValue ?
                new ObjectParameter("LokSabhaConstituencyId", lokSabhaConstituencyId) :
                new ObjectParameter("LokSabhaConstituencyId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Campaigns_GetByLokSabhaConstituencyId_Result>("sp_Campaigns_GetByLokSabhaConstituencyId", lokSabhaConstituencyIdParameter);
        }
    
        public virtual ObjectResult<sp_Campaigns_GetByPoliticalPartyId_Result> sp_Campaigns_GetByPoliticalPartyId(Nullable<long> politicalPartyId)
        {
            var politicalPartyIdParameter = politicalPartyId.HasValue ?
                new ObjectParameter("PoliticalPartyId", politicalPartyId) :
                new ObjectParameter("PoliticalPartyId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Campaigns_GetByPoliticalPartyId_Result>("sp_Campaigns_GetByPoliticalPartyId", politicalPartyIdParameter);
        }
    
        public virtual ObjectResult<sp_Campaigns_GetByVidhanSabhaConstituencyId_Result> sp_Campaigns_GetByVidhanSabhaConstituencyId(Nullable<long> vidhanSabhaConstituencyId)
        {
            var vidhanSabhaConstituencyIdParameter = vidhanSabhaConstituencyId.HasValue ?
                new ObjectParameter("VidhanSabhaConstituencyId", vidhanSabhaConstituencyId) :
                new ObjectParameter("VidhanSabhaConstituencyId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Campaigns_GetByVidhanSabhaConstituencyId_Result>("sp_Campaigns_GetByVidhanSabhaConstituencyId", vidhanSabhaConstituencyIdParameter);
        }
    
        public virtual ObjectResult<sp_Campaigns_GetByVolunteerId_Result> sp_Campaigns_GetByVolunteerId(Nullable<long> volunteerId)
        {
            var volunteerIdParameter = volunteerId.HasValue ?
                new ObjectParameter("VolunteerId", volunteerId) :
                new ObjectParameter("VolunteerId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Campaigns_GetByVolunteerId_Result>("sp_Campaigns_GetByVolunteerId", volunteerIdParameter);
        }
    
        public virtual ObjectResult<sp_Campaigns_GetByWardId_Result> sp_Campaigns_GetByWardId(Nullable<long> wardId)
        {
            var wardIdParameter = wardId.HasValue ?
                new ObjectParameter("WardId", wardId) :
                new ObjectParameter("WardId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Campaigns_GetByWardId_Result>("sp_Campaigns_GetByWardId", wardIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_CreateUser(Nullable<long> voterID, Nullable<int> politicalPartyID, Nullable<System.DateTime> dataIsCreated, Nullable<System.DateTime> dataIsUpdated, Nullable<long> createdBy, Nullable<long> modifiedBy, string userID, string password, string mobile, string fullName, Nullable<bool> isActive, Nullable<bool> isBlocked, string aadharCardNumber, Nullable<int> userTypeid, string userPhoto)
        {
            var voterIDParameter = voterID.HasValue ?
                new ObjectParameter("voterID", voterID) :
                new ObjectParameter("voterID", typeof(long));
    
            var politicalPartyIDParameter = politicalPartyID.HasValue ?
                new ObjectParameter("politicalPartyID", politicalPartyID) :
                new ObjectParameter("politicalPartyID", typeof(int));
    
            var dataIsCreatedParameter = dataIsCreated.HasValue ?
                new ObjectParameter("dataIsCreated", dataIsCreated) :
                new ObjectParameter("dataIsCreated", typeof(System.DateTime));
    
            var dataIsUpdatedParameter = dataIsUpdated.HasValue ?
                new ObjectParameter("dataIsUpdated", dataIsUpdated) :
                new ObjectParameter("dataIsUpdated", typeof(System.DateTime));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(long));
    
            var modifiedByParameter = modifiedBy.HasValue ?
                new ObjectParameter("modifiedBy", modifiedBy) :
                new ObjectParameter("modifiedBy", typeof(long));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("fullName", fullName) :
                new ObjectParameter("fullName", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            var isBlockedParameter = isBlocked.HasValue ?
                new ObjectParameter("isBlocked", isBlocked) :
                new ObjectParameter("isBlocked", typeof(bool));
    
            var aadharCardNumberParameter = aadharCardNumber != null ?
                new ObjectParameter("AadharCardNumber", aadharCardNumber) :
                new ObjectParameter("AadharCardNumber", typeof(string));
    
            var userTypeidParameter = userTypeid.HasValue ?
                new ObjectParameter("userTypeid", userTypeid) :
                new ObjectParameter("userTypeid", typeof(int));
    
            var userPhotoParameter = userPhoto != null ?
                new ObjectParameter("userPhoto", userPhoto) :
                new ObjectParameter("userPhoto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_CreateUser", voterIDParameter, politicalPartyIDParameter, dataIsCreatedParameter, dataIsUpdatedParameter, createdByParameter, modifiedByParameter, userIDParameter, passwordParameter, mobileParameter, fullNameParameter, isActiveParameter, isBlockedParameter, aadharCardNumberParameter, userTypeidParameter, userPhotoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_update_volunteerList(Nullable<int> volunteerID)
        {
            var volunteerIDParameter = volunteerID.HasValue ?
                new ObjectParameter("volunteerID", volunteerID) :
                new ObjectParameter("volunteerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_update_volunteerList", volunteerIDParameter);
        }
    
        public virtual ObjectResult<sp_getZoneByStateIDAndMUncipalCorporationID_Result> sp_getZoneByStateIDAndMUncipalCorporationID(Nullable<int> stateId, Nullable<int> mPCorporation)
        {
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("stateId", stateId) :
                new ObjectParameter("stateId", typeof(int));
    
            var mPCorporationParameter = mPCorporation.HasValue ?
                new ObjectParameter("MPCorporation", mPCorporation) :
                new ObjectParameter("MPCorporation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getZoneByStateIDAndMUncipalCorporationID_Result>("sp_getZoneByStateIDAndMUncipalCorporationID", stateIdParameter, mPCorporationParameter);
        }
    
        public virtual ObjectResult<sp_getAllParties_NoParams_Result> sp_getAllParties_NoParams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAllParties_NoParams_Result>("sp_getAllParties_NoParams");
        }
    
        public virtual ObjectResult<sp_Area_GetAll_Result> sp_Area_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Area_GetAll_Result>("sp_Area_GetAll");
        }
    
        public virtual ObjectResult<sp_Area_GetByPageInchargeId_Result> sp_Area_GetByPageInchargeId(Nullable<long> pageInchargeId)
        {
            var pageInchargeIdParameter = pageInchargeId.HasValue ?
                new ObjectParameter("PageInchargeId", pageInchargeId) :
                new ObjectParameter("PageInchargeId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Area_GetByPageInchargeId_Result>("sp_Area_GetByPageInchargeId", pageInchargeIdParameter);
        }
    
        public virtual ObjectResult<sp_Area_GetByVolunteerId_Result> sp_Area_GetByVolunteerId(Nullable<long> volunteerId)
        {
            var volunteerIdParameter = volunteerId.HasValue ?
                new ObjectParameter("VolunteerId", volunteerId) :
                new ObjectParameter("VolunteerId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Area_GetByVolunteerId_Result>("sp_Area_GetByVolunteerId", volunteerIdParameter);
        }
    
        public virtual ObjectResult<sp_Event_GetByCampaignId_Result> sp_Event_GetByCampaignId(Nullable<long> campaignId)
        {
            var campaignIdParameter = campaignId.HasValue ?
                new ObjectParameter("CampaignId", campaignId) :
                new ObjectParameter("CampaignId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Event_GetByCampaignId_Result>("sp_Event_GetByCampaignId", campaignIdParameter);
        }
    
        public virtual ObjectResult<sp_Event_GetByEventTypeId_Result> sp_Event_GetByEventTypeId(Nullable<long> eventTypeId)
        {
            var eventTypeIdParameter = eventTypeId.HasValue ?
                new ObjectParameter("EventTypeId", eventTypeId) :
                new ObjectParameter("EventTypeId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Event_GetByEventTypeId_Result>("sp_Event_GetByEventTypeId", eventTypeIdParameter);
        }
    
        public virtual ObjectResult<sp_Survey_GetAll_Result> sp_Survey_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Survey_GetAll_Result>("sp_Survey_GetAll");
        }
    
        public virtual ObjectResult<sp_searchUserLoginStatus_Result> sp_searchUserLoginStatus(Nullable<int> userTypeID, string userID)
        {
            var userTypeIDParameter = userTypeID.HasValue ?
                new ObjectParameter("userTypeID", userTypeID) :
                new ObjectParameter("userTypeID", typeof(int));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_searchUserLoginStatus_Result>("sp_searchUserLoginStatus", userTypeIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_updateLastLoginTime(Nullable<long> loginID, Nullable<System.DateTime> logoutTime)
        {
            var loginIDParameter = loginID.HasValue ?
                new ObjectParameter("loginID", loginID) :
                new ObjectParameter("loginID", typeof(long));
    
            var logoutTimeParameter = logoutTime.HasValue ?
                new ObjectParameter("logoutTime", logoutTime) :
                new ObjectParameter("logoutTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_updateLastLoginTime", loginIDParameter, logoutTimeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_updateUserLoginStatus(Nullable<int> loginID, Nullable<int> updateBy, Nullable<bool> isActive, Nullable<System.DateTime> dataIsUpdated)
        {
            var loginIDParameter = loginID.HasValue ?
                new ObjectParameter("loginID", loginID) :
                new ObjectParameter("loginID", typeof(int));
    
            var updateByParameter = updateBy.HasValue ?
                new ObjectParameter("updateBy", updateBy) :
                new ObjectParameter("updateBy", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            var dataIsUpdatedParameter = dataIsUpdated.HasValue ?
                new ObjectParameter("dataIsUpdated", dataIsUpdated) :
                new ObjectParameter("dataIsUpdated", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_updateUserLoginStatus", loginIDParameter, updateByParameter, isActiveParameter, dataIsUpdatedParameter);
        }
    
        public virtual ObjectResult<sp_GetUpcomingElections_Result> sp_GetUpcomingElections()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetUpcomingElections_Result>("sp_GetUpcomingElections");
        }
    
        public virtual ObjectResult<sp_Survey_GetByCampaignId_Result> sp_Survey_GetByCampaignId(Nullable<long> campaignId)
        {
            var campaignIdParameter = campaignId.HasValue ?
                new ObjectParameter("CampaignId", campaignId) :
                new ObjectParameter("CampaignId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Survey_GetByCampaignId_Result>("sp_Survey_GetByCampaignId", campaignIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_createSurveyQuestion(Nullable<long> surveyID, Nullable<int> questionSerial, string question, Nullable<System.DateTime> dataIsCreated, Nullable<long> createdBy, Nullable<int> questionTypeID, string op1, string op2, string op3, string op4)
        {
            var surveyIDParameter = surveyID.HasValue ?
                new ObjectParameter("surveyID", surveyID) :
                new ObjectParameter("surveyID", typeof(long));
    
            var questionSerialParameter = questionSerial.HasValue ?
                new ObjectParameter("questionSerial", questionSerial) :
                new ObjectParameter("questionSerial", typeof(int));
    
            var questionParameter = question != null ?
                new ObjectParameter("question", question) :
                new ObjectParameter("question", typeof(string));
    
            var dataIsCreatedParameter = dataIsCreated.HasValue ?
                new ObjectParameter("dataIsCreated", dataIsCreated) :
                new ObjectParameter("dataIsCreated", typeof(System.DateTime));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(long));
    
            var questionTypeIDParameter = questionTypeID.HasValue ?
                new ObjectParameter("questionTypeID", questionTypeID) :
                new ObjectParameter("questionTypeID", typeof(int));
    
            var op1Parameter = op1 != null ?
                new ObjectParameter("op1", op1) :
                new ObjectParameter("op1", typeof(string));
    
            var op2Parameter = op2 != null ?
                new ObjectParameter("op2", op2) :
                new ObjectParameter("op2", typeof(string));
    
            var op3Parameter = op3 != null ?
                new ObjectParameter("op3", op3) :
                new ObjectParameter("op3", typeof(string));
    
            var op4Parameter = op4 != null ?
                new ObjectParameter("op4", op4) :
                new ObjectParameter("op4", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_createSurveyQuestion", surveyIDParameter, questionSerialParameter, questionParameter, dataIsCreatedParameter, createdByParameter, questionTypeIDParameter, op1Parameter, op2Parameter, op3Parameter, op4Parameter);
        }
    
        public virtual ObjectResult<sp_Event_GetByCampaignIdANDEventTypeID_Result> sp_Event_GetByCampaignIdANDEventTypeID(Nullable<long> campaignId, Nullable<int> eventTypeID)
        {
            var campaignIdParameter = campaignId.HasValue ?
                new ObjectParameter("CampaignId", campaignId) :
                new ObjectParameter("CampaignId", typeof(long));
    
            var eventTypeIDParameter = eventTypeID.HasValue ?
                new ObjectParameter("eventTypeID", eventTypeID) :
                new ObjectParameter("eventTypeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Event_GetByCampaignIdANDEventTypeID_Result>("sp_Event_GetByCampaignIdANDEventTypeID", campaignIdParameter, eventTypeIDParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> sp_CheckUserInCampaign(Nullable<long> volunteerID, Nullable<long> campaignID)
        {
            var volunteerIDParameter = volunteerID.HasValue ?
                new ObjectParameter("volunteerID", volunteerID) :
                new ObjectParameter("volunteerID", typeof(long));
    
            var campaignIDParameter = campaignID.HasValue ?
                new ObjectParameter("campaignID", campaignID) :
                new ObjectParameter("campaignID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("sp_CheckUserInCampaign", volunteerIDParameter, campaignIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_createEvent(Nullable<int> eventTypeID, Nullable<long> campaignID, Nullable<System.DateTime> dataIsCreated, Nullable<long> createdBy, string eventTitle, string eventDescription, string mediaURL)
        {
            var eventTypeIDParameter = eventTypeID.HasValue ?
                new ObjectParameter("eventTypeID", eventTypeID) :
                new ObjectParameter("eventTypeID", typeof(int));
    
            var campaignIDParameter = campaignID.HasValue ?
                new ObjectParameter("campaignID", campaignID) :
                new ObjectParameter("campaignID", typeof(long));
    
            var dataIsCreatedParameter = dataIsCreated.HasValue ?
                new ObjectParameter("dataIsCreated", dataIsCreated) :
                new ObjectParameter("dataIsCreated", typeof(System.DateTime));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(long));
    
            var eventTitleParameter = eventTitle != null ?
                new ObjectParameter("eventTitle", eventTitle) :
                new ObjectParameter("eventTitle", typeof(string));
    
            var eventDescriptionParameter = eventDescription != null ?
                new ObjectParameter("eventDescription", eventDescription) :
                new ObjectParameter("eventDescription", typeof(string));
    
            var mediaURLParameter = mediaURL != null ?
                new ObjectParameter("mediaURL", mediaURL) :
                new ObjectParameter("mediaURL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_createEvent", eventTypeIDParameter, campaignIDParameter, dataIsCreatedParameter, createdByParameter, eventTitleParameter, eventDescriptionParameter, mediaURLParameter);
        }
    
        public virtual ObjectResult<sp_GetLatestNews_Result> sp_GetLatestNews()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetLatestNews_Result>("sp_GetLatestNews");
        }
    
        public virtual ObjectResult<sp_getAllBiographiesStartwithLetter_Result> sp_getAllBiographiesStartwithLetter(string nAME)
        {
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAllBiographiesStartwithLetter_Result>("sp_getAllBiographiesStartwithLetter", nAMEParameter);
        }
    
        public virtual ObjectResult<sp_getAreaListByCampignID_Result> sp_getAreaListByCampignID(Nullable<long> campignID)
        {
            var campignIDParameter = campignID.HasValue ?
                new ObjectParameter("CampignID", campignID) :
                new ObjectParameter("CampignID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAreaListByCampignID_Result>("sp_getAreaListByCampignID", campignIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_assignRelationshipBetweenVolunteerANDCampaign(Nullable<long> campaignID, Nullable<long> volunteerID, Nullable<System.DateTime> dataIsUpdated, Nullable<long> modifiedBy, Nullable<int> userTypeID, Nullable<int> insert)
        {
            var campaignIDParameter = campaignID.HasValue ?
                new ObjectParameter("campaignID", campaignID) :
                new ObjectParameter("campaignID", typeof(long));
    
            var volunteerIDParameter = volunteerID.HasValue ?
                new ObjectParameter("volunteerID", volunteerID) :
                new ObjectParameter("volunteerID", typeof(long));
    
            var dataIsUpdatedParameter = dataIsUpdated.HasValue ?
                new ObjectParameter("dataIsUpdated", dataIsUpdated) :
                new ObjectParameter("dataIsUpdated", typeof(System.DateTime));
    
            var modifiedByParameter = modifiedBy.HasValue ?
                new ObjectParameter("modifiedBy", modifiedBy) :
                new ObjectParameter("modifiedBy", typeof(long));
    
            var userTypeIDParameter = userTypeID.HasValue ?
                new ObjectParameter("userTypeID", userTypeID) :
                new ObjectParameter("userTypeID", typeof(int));
    
            var insertParameter = insert.HasValue ?
                new ObjectParameter("insert", insert) :
                new ObjectParameter("insert", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_assignRelationshipBetweenVolunteerANDCampaign", campaignIDParameter, volunteerIDParameter, dataIsUpdatedParameter, modifiedByParameter, userTypeIDParameter, insertParameter);
        }
    
        public virtual ObjectResult<sp_GetAllSectionInchargeByCampaign_Result> sp_GetAllSectionInchargeByCampaign(Nullable<long> cmpID)
        {
            var cmpIDParameter = cmpID.HasValue ?
                new ObjectParameter("cmpID", cmpID) :
                new ObjectParameter("cmpID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllSectionInchargeByCampaign_Result>("sp_GetAllSectionInchargeByCampaign", cmpIDParameter);
        }
    
        public virtual ObjectResult<sp_SurveyAnalysis_BySurveyId_Result> sp_SurveyAnalysis_BySurveyId(Nullable<long> surveyId)
        {
            var surveyIdParameter = surveyId.HasValue ?
                new ObjectParameter("SurveyId", surveyId) :
                new ObjectParameter("SurveyId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SurveyAnalysis_BySurveyId_Result>("sp_SurveyAnalysis_BySurveyId", surveyIdParameter);
        }
    
        public virtual int sp_Voters_DeleteByVoterId(Nullable<long> voterId)
        {
            var voterIdParameter = voterId.HasValue ?
                new ObjectParameter("VoterId", voterId) :
                new ObjectParameter("VoterId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Voters_DeleteByVoterId", voterIdParameter);
        }
    
        public virtual ObjectResult<sp_GetAllDataEntryOperators_Result> sp_GetAllDataEntryOperators()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllDataEntryOperators_Result>("sp_GetAllDataEntryOperators");
        }
    
        public virtual ObjectResult<sp_getWardByStateIDAndMUncipalCorporationID_Result> sp_getWardByStateIDAndMUncipalCorporationID(Nullable<int> stateId, Nullable<int> mPCorporation, Nullable<int> distictID, Nullable<int> vidhanSabhaConstituencyID)
        {
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("stateId", stateId) :
                new ObjectParameter("stateId", typeof(int));
    
            var mPCorporationParameter = mPCorporation.HasValue ?
                new ObjectParameter("MPCorporation", mPCorporation) :
                new ObjectParameter("MPCorporation", typeof(int));
    
            var distictIDParameter = distictID.HasValue ?
                new ObjectParameter("distictID", distictID) :
                new ObjectParameter("distictID", typeof(int));
    
            var vidhanSabhaConstituencyIDParameter = vidhanSabhaConstituencyID.HasValue ?
                new ObjectParameter("vidhanSabhaConstituencyID", vidhanSabhaConstituencyID) :
                new ObjectParameter("vidhanSabhaConstituencyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getWardByStateIDAndMUncipalCorporationID_Result>("sp_getWardByStateIDAndMUncipalCorporationID", stateIdParameter, mPCorporationParameter, distictIDParameter, vidhanSabhaConstituencyIDParameter);
        }
    
        public virtual ObjectResult<sp_GetAllEventTypes_Result> sp_GetAllEventTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllEventTypes_Result>("sp_GetAllEventTypes");
        }
    
        public virtual ObjectResult<sp_LoginUser_App_Result> sp_LoginUser_App(string password, string userID, Nullable<int> userType)
        {
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));
    
            var userTypeParameter = userType.HasValue ?
                new ObjectParameter("userType", userType) :
                new ObjectParameter("userType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LoginUser_App_Result>("sp_LoginUser_App", passwordParameter, userIDParameter, userTypeParameter);
        }
    
        public virtual ObjectResult<sp_PageInchargeComments_ByCampaignId_Result> sp_PageInchargeComments_ByCampaignId(Nullable<long> campaignId, Nullable<long> boothInchargeId)
        {
            var campaignIdParameter = campaignId.HasValue ?
                new ObjectParameter("CampaignId", campaignId) :
                new ObjectParameter("CampaignId", typeof(long));
    
            var boothInchargeIdParameter = boothInchargeId.HasValue ?
                new ObjectParameter("BoothInchargeId", boothInchargeId) :
                new ObjectParameter("BoothInchargeId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PageInchargeComments_ByCampaignId_Result>("sp_PageInchargeComments_ByCampaignId", campaignIdParameter, boothInchargeIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> submitSurveyResponse(Nullable<long> surveyQuesID, Nullable<long> surveyQuestionOptionId, Nullable<System.DateTime> dataIsCreated, Nullable<long> createdBy)
        {
            var surveyQuesIDParameter = surveyQuesID.HasValue ?
                new ObjectParameter("surveyQuesID", surveyQuesID) :
                new ObjectParameter("surveyQuesID", typeof(long));
    
            var surveyQuestionOptionIdParameter = surveyQuestionOptionId.HasValue ?
                new ObjectParameter("SurveyQuestionOptionId", surveyQuestionOptionId) :
                new ObjectParameter("SurveyQuestionOptionId", typeof(long));
    
            var dataIsCreatedParameter = dataIsCreated.HasValue ?
                new ObjectParameter("dataIsCreated", dataIsCreated) :
                new ObjectParameter("dataIsCreated", typeof(System.DateTime));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("submitSurveyResponse", surveyQuesIDParameter, surveyQuestionOptionIdParameter, dataIsCreatedParameter, createdByParameter);
        }
    
        public virtual ObjectResult<sp_getPageInchargeLocation_Result> sp_getPageInchargeLocation(Nullable<long> campaignId, Nullable<long> pageInchargeId, Nullable<System.DateTime> dataIsCreated)
        {
            var campaignIdParameter = campaignId.HasValue ?
                new ObjectParameter("CampaignId", campaignId) :
                new ObjectParameter("CampaignId", typeof(long));
    
            var pageInchargeIdParameter = pageInchargeId.HasValue ?
                new ObjectParameter("PageInchargeId", pageInchargeId) :
                new ObjectParameter("PageInchargeId", typeof(long));
    
            var dataIsCreatedParameter = dataIsCreated.HasValue ?
                new ObjectParameter("dataIsCreated", dataIsCreated) :
                new ObjectParameter("dataIsCreated", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getPageInchargeLocation_Result>("sp_getPageInchargeLocation", campaignIdParameter, pageInchargeIdParameter, dataIsCreatedParameter);
        }
    
        public virtual ObjectResult<sp_SurveyQuestion_GetBySurveyId_Result> sp_SurveyQuestion_GetBySurveyId(Nullable<long> surveyId)
        {
            var surveyIdParameter = surveyId.HasValue ?
                new ObjectParameter("SurveyId", surveyId) :
                new ObjectParameter("SurveyId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SurveyQuestion_GetBySurveyId_Result>("sp_SurveyQuestion_GetBySurveyId", surveyIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_GetVotersByAge(Nullable<long> lokSabhaID, Nullable<long> vidhanSabhaID, Nullable<long> wardID, Nullable<long> year)
        {
            var lokSabhaIDParameter = lokSabhaID.HasValue ?
                new ObjectParameter("lokSabhaID", lokSabhaID) :
                new ObjectParameter("lokSabhaID", typeof(long));
    
            var vidhanSabhaIDParameter = vidhanSabhaID.HasValue ?
                new ObjectParameter("vidhanSabhaID", vidhanSabhaID) :
                new ObjectParameter("vidhanSabhaID", typeof(long));
    
            var wardIDParameter = wardID.HasValue ?
                new ObjectParameter("wardID", wardID) :
                new ObjectParameter("wardID", typeof(long));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_GetVotersByAge", lokSabhaIDParameter, vidhanSabhaIDParameter, wardIDParameter, yearParameter);
        }
    
        public virtual ObjectResult<sp_Voters_GetAll_Result> sp_Voters_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Voters_GetAll_Result>("sp_Voters_GetAll");
        }
    
        public virtual ObjectResult<sp_Voters_GetByAreaId_Result> sp_Voters_GetByAreaId(Nullable<long> areaId)
        {
            var areaIdParameter = areaId.HasValue ?
                new ObjectParameter("AreaId", areaId) :
                new ObjectParameter("AreaId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Voters_GetByAreaId_Result>("sp_Voters_GetByAreaId", areaIdParameter);
        }
    
        public virtual ObjectResult<sp_Voters_GetById_Result> sp_Voters_GetById(Nullable<long> voterId)
        {
            var voterIdParameter = voterId.HasValue ?
                new ObjectParameter("VoterId", voterId) :
                new ObjectParameter("VoterId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Voters_GetById_Result>("sp_Voters_GetById", voterIdParameter);
        }
    
        public virtual ObjectResult<sp_Voters_GetByLokSabhaConstituencyId_Result> sp_Voters_GetByLokSabhaConstituencyId(Nullable<long> lokSabhaConstituencyId)
        {
            var lokSabhaConstituencyIdParameter = lokSabhaConstituencyId.HasValue ?
                new ObjectParameter("LokSabhaConstituencyId", lokSabhaConstituencyId) :
                new ObjectParameter("LokSabhaConstituencyId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Voters_GetByLokSabhaConstituencyId_Result>("sp_Voters_GetByLokSabhaConstituencyId", lokSabhaConstituencyIdParameter);
        }
    
        public virtual ObjectResult<sp_Voters_GetByStateId_Result> sp_Voters_GetByStateId(Nullable<long> stateId)
        {
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("StateId", stateId) :
                new ObjectParameter("StateId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Voters_GetByStateId_Result>("sp_Voters_GetByStateId", stateIdParameter);
        }
    
        public virtual ObjectResult<sp_Voters_GetByVidhanSabhaConstituencyId_Result> sp_Voters_GetByVidhanSabhaConstituencyId(Nullable<long> vidhanSabhaConstituencyId)
        {
            var vidhanSabhaConstituencyIdParameter = vidhanSabhaConstituencyId.HasValue ?
                new ObjectParameter("VidhanSabhaConstituencyId", vidhanSabhaConstituencyId) :
                new ObjectParameter("VidhanSabhaConstituencyId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Voters_GetByVidhanSabhaConstituencyId_Result>("sp_Voters_GetByVidhanSabhaConstituencyId", vidhanSabhaConstituencyIdParameter);
        }
    
        public virtual ObjectResult<sp_Voters_GetByWardId_Result> sp_Voters_GetByWardId(Nullable<long> wardId)
        {
            var wardIdParameter = wardId.HasValue ?
                new ObjectParameter("WardId", wardId) :
                new ObjectParameter("WardId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Voters_GetByWardId_Result>("sp_Voters_GetByWardId", wardIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Voters_UpdateDetail(Nullable<long> campaignId, Nullable<long> pageInchargeId, Nullable<long> voterId, string voterName, string voterLastName, string father_HusbandName, Nullable<int> genderId, Nullable<System.DateTime> dOB, string address, string phone, string changeType, string commentDetail, Nullable<double> latitude, Nullable<double> longitude, Nullable<System.DateTime> dataIsCreated, Nullable<long> volunteerID, string plotNo)
        {
            var campaignIdParameter = campaignId.HasValue ?
                new ObjectParameter("CampaignId", campaignId) :
                new ObjectParameter("CampaignId", typeof(long));
    
            var pageInchargeIdParameter = pageInchargeId.HasValue ?
                new ObjectParameter("PageInchargeId", pageInchargeId) :
                new ObjectParameter("PageInchargeId", typeof(long));
    
            var voterIdParameter = voterId.HasValue ?
                new ObjectParameter("VoterId", voterId) :
                new ObjectParameter("VoterId", typeof(long));
    
            var voterNameParameter = voterName != null ?
                new ObjectParameter("VoterName", voterName) :
                new ObjectParameter("VoterName", typeof(string));
    
            var voterLastNameParameter = voterLastName != null ?
                new ObjectParameter("VoterLastName", voterLastName) :
                new ObjectParameter("VoterLastName", typeof(string));
    
            var father_HusbandNameParameter = father_HusbandName != null ?
                new ObjectParameter("Father_HusbandName", father_HusbandName) :
                new ObjectParameter("Father_HusbandName", typeof(string));
    
            var genderIdParameter = genderId.HasValue ?
                new ObjectParameter("GenderId", genderId) :
                new ObjectParameter("GenderId", typeof(int));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var changeTypeParameter = changeType != null ?
                new ObjectParameter("ChangeType", changeType) :
                new ObjectParameter("ChangeType", typeof(string));
    
            var commentDetailParameter = commentDetail != null ?
                new ObjectParameter("CommentDetail", commentDetail) :
                new ObjectParameter("CommentDetail", typeof(string));
    
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("latitude", latitude) :
                new ObjectParameter("latitude", typeof(double));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("longitude", longitude) :
                new ObjectParameter("longitude", typeof(double));
    
            var dataIsCreatedParameter = dataIsCreated.HasValue ?
                new ObjectParameter("dataIsCreated", dataIsCreated) :
                new ObjectParameter("dataIsCreated", typeof(System.DateTime));
    
            var volunteerIDParameter = volunteerID.HasValue ?
                new ObjectParameter("volunteerID", volunteerID) :
                new ObjectParameter("volunteerID", typeof(long));
    
            var plotNoParameter = plotNo != null ?
                new ObjectParameter("plotNo", plotNo) :
                new ObjectParameter("plotNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Voters_UpdateDetail", campaignIdParameter, pageInchargeIdParameter, voterIdParameter, voterNameParameter, voterLastNameParameter, father_HusbandNameParameter, genderIdParameter, dOBParameter, addressParameter, phoneParameter, changeTypeParameter, commentDetailParameter, latitudeParameter, longitudeParameter, dataIsCreatedParameter, volunteerIDParameter, plotNoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Voters_VerifyByPageIncharge(Nullable<long> campaignId, Nullable<long> pageInchargeId, Nullable<long> voterId, string changeType, string commentDetail, Nullable<double> latitude, Nullable<double> longitude, Nullable<System.DateTime> dataIsCreated)
        {
            var campaignIdParameter = campaignId.HasValue ?
                new ObjectParameter("CampaignId", campaignId) :
                new ObjectParameter("CampaignId", typeof(long));
    
            var pageInchargeIdParameter = pageInchargeId.HasValue ?
                new ObjectParameter("PageInchargeId", pageInchargeId) :
                new ObjectParameter("PageInchargeId", typeof(long));
    
            var voterIdParameter = voterId.HasValue ?
                new ObjectParameter("VoterId", voterId) :
                new ObjectParameter("VoterId", typeof(long));
    
            var changeTypeParameter = changeType != null ?
                new ObjectParameter("ChangeType", changeType) :
                new ObjectParameter("ChangeType", typeof(string));
    
            var commentDetailParameter = commentDetail != null ?
                new ObjectParameter("CommentDetail", commentDetail) :
                new ObjectParameter("CommentDetail", typeof(string));
    
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("latitude", latitude) :
                new ObjectParameter("latitude", typeof(double));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("longitude", longitude) :
                new ObjectParameter("longitude", typeof(double));
    
            var dataIsCreatedParameter = dataIsCreated.HasValue ?
                new ObjectParameter("dataIsCreated", dataIsCreated) :
                new ObjectParameter("dataIsCreated", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Voters_VerifyByPageIncharge", campaignIdParameter, pageInchargeIdParameter, voterIdParameter, changeTypeParameter, commentDetailParameter, latitudeParameter, longitudeParameter, dataIsCreatedParameter);
        }
    
        public virtual ObjectResult<sp_GetVoters_List_Result> sp_GetVoters_List(string voterIdNumber, Nullable<long> createdBy, Nullable<System.DateTime> createdDate)
        {
            var voterIdNumberParameter = voterIdNumber != null ?
                new ObjectParameter("VoterIdNumber", voterIdNumber) :
                new ObjectParameter("VoterIdNumber", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(long));
    
            var createdDateParameter = createdDate.HasValue ?
                new ObjectParameter("createdDate", createdDate) :
                new ObjectParameter("createdDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetVoters_List_Result>("sp_GetVoters_List", voterIdNumberParameter, createdByParameter, createdDateParameter);
        }
    
        public virtual ObjectResult<sp_getVoterDetailsByVoterID_Result> sp_getVoterDetailsByVoterID(string voterIDNumber)
        {
            var voterIDNumberParameter = voterIDNumber != null ?
                new ObjectParameter("voterIDNumber", voterIDNumber) :
                new ObjectParameter("voterIDNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getVoterDetailsByVoterID_Result>("sp_getVoterDetailsByVoterID", voterIDNumberParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_insertVoterListExcel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_insertVoterListExcel");
        }
    
        public virtual ObjectResult<sp_Voters_GetByPageInchargeId_Result> sp_Voters_GetByPageInchargeId(Nullable<long> pageInchargeId)
        {
            var pageInchargeIdParameter = pageInchargeId.HasValue ?
                new ObjectParameter("PageInchargeId", pageInchargeId) :
                new ObjectParameter("PageInchargeId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Voters_GetByPageInchargeId_Result>("sp_Voters_GetByPageInchargeId", pageInchargeIdParameter);
        }
    
        public virtual ObjectResult<sp_SectionIncharge_GetAllByBoothIncharge_Result> sp_SectionIncharge_GetAllByBoothIncharge(Nullable<long> campaignId, Nullable<long> boothInchargeId)
        {
            var campaignIdParameter = campaignId.HasValue ?
                new ObjectParameter("CampaignId", campaignId) :
                new ObjectParameter("CampaignId", typeof(long));
    
            var boothInchargeIdParameter = boothInchargeId.HasValue ?
                new ObjectParameter("BoothInchargeId", boothInchargeId) :
                new ObjectParameter("BoothInchargeId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SectionIncharge_GetAllByBoothIncharge_Result>("sp_SectionIncharge_GetAllByBoothIncharge", campaignIdParameter, boothInchargeIdParameter);
        }
    
        public virtual ObjectResult<sp_LoginUser_Result> sp_LoginUser(string password, string userID)
        {
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LoginUser_Result>("sp_LoginUser", passwordParameter, userIDParameter);
        }
    
        public virtual ObjectResult<sp_getPoolingBoothByCampignID_Result> sp_getPoolingBoothByCampignID(Nullable<long> campignID)
        {
            var campignIDParameter = campignID.HasValue ?
                new ObjectParameter("CampignID", campignID) :
                new ObjectParameter("CampignID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getPoolingBoothByCampignID_Result>("sp_getPoolingBoothByCampignID", campignIDParameter);
        }
    
        public virtual ObjectResult<sp_GetVolunteers_Result> sp_GetVolunteers(Nullable<int> politicalParty, Nullable<int> stateID, Nullable<int> vidhanSabhaConstituencyID, Nullable<int> lokSabhaConstituencyID, Nullable<int> campaignID)
        {
            var politicalPartyParameter = politicalParty.HasValue ?
                new ObjectParameter("politicalParty", politicalParty) :
                new ObjectParameter("politicalParty", typeof(int));
    
            var stateIDParameter = stateID.HasValue ?
                new ObjectParameter("stateID", stateID) :
                new ObjectParameter("stateID", typeof(int));
    
            var vidhanSabhaConstituencyIDParameter = vidhanSabhaConstituencyID.HasValue ?
                new ObjectParameter("vidhanSabhaConstituencyID", vidhanSabhaConstituencyID) :
                new ObjectParameter("vidhanSabhaConstituencyID", typeof(int));
    
            var lokSabhaConstituencyIDParameter = lokSabhaConstituencyID.HasValue ?
                new ObjectParameter("lokSabhaConstituencyID", lokSabhaConstituencyID) :
                new ObjectParameter("lokSabhaConstituencyID", typeof(int));
    
            var campaignIDParameter = campaignID.HasValue ?
                new ObjectParameter("campaignID", campaignID) :
                new ObjectParameter("campaignID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetVolunteers_Result>("sp_GetVolunteers", politicalPartyParameter, stateIDParameter, vidhanSabhaConstituencyIDParameter, lokSabhaConstituencyIDParameter, campaignIDParameter);
        }
    
        public virtual ObjectResult<sp_getAllRelationshipsInCampaignByUserType_Result> sp_getAllRelationshipsInCampaignByUserType(Nullable<int> userTypeID, Nullable<int> cmpID)
        {
            var userTypeIDParameter = userTypeID.HasValue ?
                new ObjectParameter("userTypeID", userTypeID) :
                new ObjectParameter("userTypeID", typeof(int));
    
            var cmpIDParameter = cmpID.HasValue ?
                new ObjectParameter("cmpID", cmpID) :
                new ObjectParameter("cmpID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAllRelationshipsInCampaignByUserType_Result>("sp_getAllRelationshipsInCampaignByUserType", userTypeIDParameter, cmpIDParameter);
        }
    }
}
