//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enquiry
    {
        public long enquiryID { get; set; }
        public int enquiryTypeID { get; set; }
        public string enquirerName { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string enquiryDescription { get; set; }
        public System.DateTime dataIsCreated { get; set; }
        public System.DateTime dataIsUpdated { get; set; }
        public long modifiedBy { get; set; }
        public bool isTaskComplete { get; set; }
    
        public virtual enquiryType enquiryType { get; set; }
        public virtual loginVolunteer loginVolunteer { get; set; }
    }
}
