//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventMedia
    {
        public long eventMediaID { get; set; }
        public string mediaName { get; set; }
        public string mediaURL { get; set; }
        public System.DateTime dataIsUpdated { get; set; }
        public System.DateTime dataIsCreated { get; set; }
        public long createdBy { get; set; }
        public long eventID { get; set; }
    
        public virtual @event @event { get; set; }
        public virtual loginVolunteer loginVolunteer { get; set; }
    }
}
