//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class excel
    {
        public int ID { get; set; }
        public string statename { get; set; }
        public string districtname { get; set; }
        public string loksabhaname { get; set; }
        public string vidhansabhaname { get; set; }
        public string municipalcorporationname { get; set; }
        public string zonename { get; set; }
        public string wardname { get; set; }
        public string pollingboothname { get; set; }
        public string areaname { get; set; }
        public string voterfirstname { get; set; }
        public string voterlastname { get; set; }
        public string plotno { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> dateofbirth { get; set; }
        public string voteridnumber { get; set; }
        public string age { get; set; }
        public string wardno { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string zipCode { get; set; }
        public string FatherName { get; set; }
    }
}
