//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pageInchargeComment
    {
        public long commentID { get; set; }
        public long voterID { get; set; }
        public Nullable<long> areaID { get; set; }
        public string plotNo { get; set; }
        public string comment { get; set; }
        public string streetNo { get; set; }
        public System.DateTime dataIsCreated { get; set; }
        public System.DateTime dataIsUpdated { get; set; }
        public long createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public bool isChanged { get; set; }
        public bool isVerified { get; set; }
        public bool isModified { get; set; }
        public long CampaignId { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string ChangeType { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<long> volunteerID { get; set; }
    
        public virtual loginVolunteer loginVolunteer { get; set; }
        public virtual loginVolunteer loginVolunteer1 { get; set; }
        public virtual volunteerList volunteerList { get; set; }
    }
}
