//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class politicalPartyAddress
    {
        public int politicalPartyAddressID { get; set; }
        public int politicalPartyID { get; set; }
        public int districtID { get; set; }
        public int stateID { get; set; }
        public string plotNo { get; set; }
        public string streetNo { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public Nullable<int> pincode { get; set; }
        public System.DateTime dataIsCreated { get; set; }
        public System.DateTime dataIsUpdated { get; set; }
        public long createdBy { get; set; }
        public long modifiedBy { get; set; }
        public bool isActive { get; set; }
        public bool isDelete { get; set; }
        public string telephone { get; set; }
        public bool isHeadOffice { get; set; }
    
        public virtual district district { get; set; }
        public virtual loginVolunteer loginVolunteer { get; set; }
        public virtual loginVolunteer loginVolunteer1 { get; set; }
        public virtual politicalParty politicalParty { get; set; }
        public virtual state state { get; set; }
    }
}
