//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pollingBooth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pollingBooth()
        {
            this.pollingBooth_andInchargRelationship = new HashSet<pollingBooth_andInchargRelationship>();
        }
    
        public long pollingBoothID { get; set; }
        public string pollingBoothName { get; set; }
        public int vidhanSabhaConstituencyID { get; set; }
        public int lokSabhaConstituencyID { get; set; }
        public int wardID { get; set; }
        public int districtID { get; set; }
        public int stateID { get; set; }
        public System.DateTime dataIsCreated { get; set; }
        public System.DateTime dataIsUpdated { get; set; }
        public long createdBy { get; set; }
        public long modifiedBy { get; set; }
        public bool isActive { get; set; }
        public string plotNo { get; set; }
        public string streetNo { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public int pincode { get; set; }
    
        public virtual district district { get; set; }
        public virtual loginVolunteer loginVolunteer { get; set; }
        public virtual loginVolunteer loginVolunteer1 { get; set; }
        public virtual lokSabhaConstituency lokSabhaConstituency { get; set; }
        public virtual state state { get; set; }
        public virtual vidhanSabhaConstituency vidhanSabhaConstituency { get; set; }
        public virtual wardConstituency wardConstituency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pollingBooth_andInchargRelationship> pollingBooth_andInchargRelationship { get; set; }
    }
}
