//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userRight
    {
        public int role_action_id { get; set; }
        public int userTypeID { get; set; }
        public string controller_name { get; set; }
        public string action_name { get; set; }
    }
}
